#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SourceAPI.Generators
{
    [Generator]
    public class AuditableEntityGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // partial classを持つクラスをフィルタ
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateClass(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // ソースコード生成
            context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source!, spc));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword);
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null)
                return null;

            // BaseEntityを継承しているか確認
            if (!InheritsFromBaseEntity(symbol))
                return null;

            return symbol;
        }

        private static bool InheritsFromBaseEntity(INamedTypeSymbol classSymbol)
        {
            var baseType = classSymbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "BaseEntity")
                    return true;
                baseType = baseType.BaseType;
            }
            return false;
        }

        private static void Execute(INamedTypeSymbol classSymbol, SourceProductionContext context)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            // partial classでヘルパーメソッドを生成
            var source = GeneratePartialClass(namespaceName, className);
            context.AddSource($"{className}.g.cs", source);
        }

        private static string GeneratePartialClass(string namespaceName, string className)
        {
            return $@"// <auto-generated/>
#nullable enable

namespace {namespaceName}
{{
    /// <summary>
    /// Source Generator により自動生成されたpartial class
    /// </summary>
    public partial class {className}
    {{
        /// <summary>
        /// エンティティがアクティブ（削除されていない）かどうか
        /// </summary>
        public bool IsActive => !IsDeleted;

        /// <summary>
        /// エンティティを論理削除としてマーク
        /// </summary>
        public void MarkAsDeleted()
        {{
            IsDeleted = true;
            DeletedAt = System.DateTime.UtcNow;
        }}

        /// <summary>
        /// 削除マークを解除
        /// </summary>
        public void Restore()
        {{
            IsDeleted = false;
            DeletedAt = null;
        }}

        /// <summary>
        /// エンティティの年齢（作成からの経過時間）
        /// </summary>
        public System.TimeSpan Age => System.DateTime.UtcNow - CreatedAt;

        /// <summary>
        /// 最後の更新からの経過時間
        /// </summary>
        public System.TimeSpan TimeSinceLastUpdate => System.DateTime.UtcNow - UpdatedAt;
    }}
}}
";
        }
    }
}