#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SourceAPI.Generators
{
    [Generator]
    public class AuditableEntityGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // [AuditableEntity]属性を持つpartial classをフィルタ
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateClass(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // 監査フィールドとヘルパーメソッドを生成
            context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source!, spc));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword) &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null)
                return null;

            // [AuditableEntity]属性を持つか確認
            if (!HasAuditableEntityAttribute(symbol))
                return null;

            return symbol;
        }

        private static bool HasAuditableEntityAttribute(INamedTypeSymbol classSymbol)
        {
            return classSymbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "AuditableEntityAttribute");
        }

        private static void Execute(INamedTypeSymbol classSymbol, SourceProductionContext context)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;

            // partial classで監査フィールドとヘルパーメソッドを生成
            var source = GeneratePartialClass(namespaceName, className);
            context.AddSource($"{className}.g.cs", source);
        }

        private static string GeneratePartialClass(string namespaceName, string className)
        {
            return $@"// <auto-generated/>
#nullable enable

namespace {namespaceName}
{{
    /// <summary>
    /// Source Generator により自動生成されたpartial class
    /// 監査フィールドとヘルパーメソッドを提供
    /// </summary>
    public partial class {className} : SourceAPI.Interfaces.IAuditableEntity
    {{
        // === 監査フィールド ===
        /// <summary>
        /// 作成日時
        /// </summary>
        public System.DateTime CreatedAt {{ get; set; }}

        /// <summary>
        /// 更新日時
        /// </summary>
        public System.DateTime UpdatedAt {{ get; set; }}

        /// <summary>
        /// 論理削除フラグ
        /// </summary>
        public bool IsDeleted {{ get; set; }}

        /// <summary>
        /// 削除日時
        /// </summary>
        public System.DateTime? DeletedAt {{ get; set; }}

        // === ヘルパープロパティ ===
        /// <summary>
        /// エンティティがアクティブ（削除されていない）かどうか
        /// </summary>
        public bool IsActive => !IsDeleted;

        /// <summary>
        /// 最後の更新からの経過時間
        /// </summary>
        public System.TimeSpan TimeSinceLastUpdate => System.DateTime.UtcNow - UpdatedAt;

        // === ヘルパーメソッド ===
        /// <summary>
        /// エンティティを論理削除としてマーク
        /// </summary>
        public void MarkAsDeleted()
        {{
            IsDeleted = true;
            DeletedAt = System.DateTime.UtcNow;
        }}

        /// <summary>
        /// 削除マークを解除
        /// </summary>
        public void Restore()
        {{
            IsDeleted = false;
            DeletedAt = null;
        }}
    }}
}}
";
        }
    }
}