#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;

namespace SourceAPI.Generators
{
    [Generator]
    public class RepositoryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // [GenerateRepository]属性を持つpartial classをフィルタ
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidateClass(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // Repositoryインターフェースと実装クラスを生成
            context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source!, spc));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null)
                return null;

            // [GenerateRepository]属性を持つか確認
            if (!HasGenerateRepositoryAttribute(symbol))
                return null;

            // SourceAPI.Models.DB namespaceのみを対象にする
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            if (namespaceName != "SourceAPI.Models.DB")
                return null;

            return symbol;
        }

        private static bool HasGenerateRepositoryAttribute(INamedTypeSymbol classSymbol)
        {
            return classSymbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "GenerateRepositoryAttribute");
        }

        private static void Execute(INamedTypeSymbol classSymbol, SourceProductionContext context)
        {
            var className = classSymbol.Name;
            var repositoryName = $"{className}Repository";
            var interfaceName = $"I{repositoryName}";

            // Idプロパティの型を取得（デフォルトはint）
            var idProperty = classSymbol.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == "Id");
            var idType = idProperty?.Type.ToDisplayString() ?? "int";

            // インターフェースを生成
            var interfaceSource = GenerateInterface(className, interfaceName, idType);
            context.AddSource($"{interfaceName}.g.cs", interfaceSource);

            // 実装クラスを生成
            var implementationSource = GenerateImplementation(className, repositoryName, interfaceName, idType);
            context.AddSource($"{repositoryName}.g.cs", implementationSource);
        }

        private static string GenerateInterface(string entityName, string interfaceName, string idType)
        {
            return $@"// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using SourceAPI.Models.DB;

namespace SourceAPI.Repositories.Interfaces
{{
    /// <summary>
    /// {entityName}のRepositoryインターフェース
    /// Source Generatorにより自動生成
    /// </summary>
    public interface {interfaceName}
    {{
        /// <summary>
        /// 条件に一致する{entityName}のリストを取得
        /// </summary>
        /// <param name=""predicate"">フィルタ条件（nullの場合は全件取得）</param>
        /// <param name=""orderBy"">ソート対象のプロパティ（nullの場合はソートなし）</param>
        /// <param name=""isAscending"">昇順の場合true、降順の場合false（デフォルト: true）</param>
        /// <returns>{entityName}のリスト（エラー時はnull）</returns>
        System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<{entityName}>?> GetAsync(System.Linq.Expressions.Expression<System.Func<{entityName}, bool>>? predicate = null, System.Linq.Expressions.Expression<System.Func<{entityName}, object>>? orderBy = null, bool isAscending = true);

        /// <summary>
        /// IDで{entityName}を取得
        /// </summary>
        /// <param name=""id"">エンティティのID</param>
        /// <returns>{entityName}（見つからない場合やエラー時はnull）</returns>
        System.Threading.Tasks.Task<{entityName}?> GetByIdAsync({idType} id);

        /// <summary>
        /// 新しい{entityName}を作成
        /// </summary>
        /// <param name=""{ToCamelCase(entityName)}"">作成する{entityName}</param>
        /// <returns>成功時true、失敗時false</returns>
        System.Threading.Tasks.Task<bool> CreateAsync({entityName} {ToCamelCase(entityName)});

        /// <summary>
        /// {entityName}を更新
        /// </summary>
        /// <param name=""{ToCamelCase(entityName)}"">更新する{entityName}</param>
        /// <returns>成功時true、失敗時false</returns>
        System.Threading.Tasks.Task<bool> UpdateAsync({entityName} {ToCamelCase(entityName)});

        /// <summary>
        /// {entityName}を削除（論理削除）
        /// </summary>
        /// <param name=""{ToCamelCase(entityName)}"">削除する{entityName}</param>
        /// <returns>成功時true、失敗時false</returns>
        System.Threading.Tasks.Task<bool> DeleteAsync({entityName} {ToCamelCase(entityName)});

        /// <summary>
        /// 指定されたIDの{entityName}が存在するか確認
        /// </summary>
        /// <param name=""id"">エンティティのID</param>
        /// <returns>存在する場合true（エラー時はfalse）</returns>
        System.Threading.Tasks.Task<bool> ExistsAsync({idType} id);

        /// <summary>
        /// クエリ可能な{entityName}のIQueryableを取得
        /// 複雑なクエリ（複数カラムソート、ページング等）を構築する場合に使用
        /// </summary>
        /// <returns>{entityName}のIQueryable</returns>
        System.Linq.IQueryable<{entityName}> GetQueryable();
    }}
}}
";
        }

        private static string GenerateImplementation(string entityName, string repositoryName, string interfaceName, string idType)
        {
            var dbSetName = $"{entityName}s"; // 複数形に変換（簡易版）
            var paramName = ToCamelCase(entityName);

            return $@"// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SourceAPI.Data;
using SourceAPI.Models.DB;
using SourceAPI.Repositories.Interfaces;

namespace SourceAPI.Repositories
{{
    /// <summary>
    /// {entityName}のRepository実装クラス
    /// Source Generatorにより自動生成
    /// </summary>
    public class {repositoryName} : {interfaceName}
    {{
        private readonly AppDbContext _context;
        private readonly ILogger<{repositoryName}> _logger;

        public {repositoryName}(AppDbContext context, ILogger<{repositoryName}> logger)
        {{
            _context = context;
            _logger = logger;
        }}

        public async System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<{entityName}>?> GetAsync(System.Linq.Expressions.Expression<System.Func<{entityName}, bool>>? predicate = null, System.Linq.Expressions.Expression<System.Func<{entityName}, object>>? orderBy = null, bool isAscending = true)
        {{
            try
            {{
                var query = _context.{dbSetName}.AsQueryable();

                // フィルタ条件を適用
                if (predicate != null)
                {{
                    query = query.Where(predicate);
                }}

                // ソート条件を適用
                if (orderBy != null)
                {{
                    query = isAscending
                        ? query.OrderBy(orderBy)
                        : query.OrderByDescending(orderBy);
                }}

                return await query.ToListAsync();
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の一覧取得に失敗しました"");
                return null;
            }}
        }}

        public async System.Threading.Tasks.Task<{entityName}?> GetByIdAsync({idType} id)
        {{
            try
            {{
                return await _context.{dbSetName}.FindAsync(id);
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の取得に失敗しました。ID: {{Id}}"", id);
                return null;
            }}
        }}

        public async System.Threading.Tasks.Task<bool> CreateAsync({entityName} {paramName})
        {{
            try
            {{
                _context.{dbSetName}.Add({paramName});
                await _context.SaveChangesAsync();
                _logger.LogInformation(""{entityName}を作成しました。ID: {{Id}}"", {paramName}.Id);
                return true;
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の作成に失敗しました"");
                return false;
            }}
        }}

        public async System.Threading.Tasks.Task<bool> UpdateAsync({entityName} {paramName})
        {{
            try
            {{
                _context.{dbSetName}.Update({paramName});
                await _context.SaveChangesAsync();
                _logger.LogInformation(""{entityName}を更新しました。ID: {{Id}}"", {paramName}.Id);
                return true;
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の更新に失敗しました。ID: {{Id}}"", {paramName}.Id);
                return false;
            }}
        }}

        public async System.Threading.Tasks.Task<bool> DeleteAsync({entityName} {paramName})
        {{
            try
            {{
                // 論理削除（ソフトデリート）
                {paramName}.IsDeleted = true;
                {paramName}.DeletedAt = System.DateTime.UtcNow;
                _context.{dbSetName}.Update({paramName});
                await _context.SaveChangesAsync();
                _logger.LogInformation(""{entityName}を削除しました。ID: {{Id}}"", {paramName}.Id);
                return true;
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の削除に失敗しました。ID: {{Id}}"", {paramName}.Id);
                return false;
            }}
        }}

        public async System.Threading.Tasks.Task<bool> ExistsAsync({idType} id)
        {{
            try
            {{
                return await _context.{dbSetName}.AnyAsync(p => p.Id == id);
            }}
            catch (System.Exception ex)
            {{
                _logger.LogError(ex, ""{entityName}の存在確認に失敗しました。ID: {{Id}}"", id);
                return false;
            }}
        }}

        public System.Linq.IQueryable<{entityName}> GetQueryable()
        {{
            return _context.{dbSetName}.AsQueryable();
        }}
    }}
}}
";
        }

        private static string ToCamelCase(string str)
        {
            if (string.IsNullOrEmpty(str) || char.IsLower(str[0]))
                return str;

            return char.ToLower(str[0]) + str.Substring(1);
        }
    }
}
